[package]
name = "rate"
version = "0.2.0"
authors = ["Gris Ge <cnfourt@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0"
nispor = "1.2.8"
bytesize = "1.1"
